name: corproots
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 10.10.0+30

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts:
  shared_preferences: ^2.0.6
  http: ^0.13.3
  carousel_slider: ^4.0.0
  flutter_local_notifications: ^8.1.1+1
  overlay_support: ^1.2.1
  double_back_to_close: ^2.0.0
  otp_text_field: ^1.1.1
  font_awesome_flutter: ^9.1.0
  rounded_loading_button: ^2.0.5
  file_picker: ^4.0.0
  cool_alert: ^1.1.0
  webview_flutter: ^2.0.12
  cached_network_image: ^3.1.0
  camera:
  badges: ^2.0.1
  flutter_summernote: ^1.0.0
  permission_handler: ^8.1.4+2
  basic_utils: ^3.4.0
  url_launcher: ^6.0.9
  syncfusion_flutter_pdfviewer: ^19.2.57-beta
  flutter_html: ^2.1.1
  flutter_downloader: ^1.6.1
  flutter_contacts: ^1.1.1+2
  razorpay_flutter: ^1.2.7
  fluttertoast: ^8.0.8


  open_file: ^3.2.1
  flutter_html_to_pdf: ^0.7.0
  modal_bottom_sheet: ^2.0.0
  youtube_player_flutter: ^8.0.0
  whatsapp_unilink: ^2.0.0
  string_extensions: ^0.3.0

  firebase_auth:
  firebase_core:
  firebase_database:
  firebase_messaging:
  cloud_firestore:
  firebase_installations: ^16.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets_files/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
